User production to run servers (flask and react)
RedHatQE/hive-claim-manager pull request #5
Opened 2024-05-20 21:33 UTC by myakove

2024-05-20 21:33 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest build-container`: Retest build-container

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-05-20 21:38 UTC, myakove commented
/verified

2024-05-20 21:39 UTC, myakove commented
pre-commit.ci run

2024-05-20 21:57 UTC, myakove commented
/verified

2024-05-21 07:49 UTC, rnetser requested changes

2024-05-21 07:49 UTC, rnetser commented on api/api.py
> +# with app.app_context():
leftovers?

2024-05-21 07:49 UTC, rnetser commented on api/utils.py
> +        return {"kubeoncig": ""}
```suggestion
        return {"kubeconfig": ""}
```

2024-05-21 08:22 UTC, myakove commented
/verified

2024-05-21 08:39 UTC, rnetser approved these changes

2024-05-21 08:39 UTC, merged

2024-05-21 08:44 UTC, msi-b1 commented
New container for quay.io/redhat_msi/hive-claim-manager:latest published